services:
  - type: web
    name: expancify-backend
    rootDir: backend
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CLIENT_ORIGIN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
